### ISSUE TITLE
Create a new help menu

### ISSUE THREAD

**Issue by AstroOrbis** [AstroOrbis/Hashy#2]

**Comment by kaustubhmallik** [comment]
Hi @AstroOrbis , is it still relevant. I'm trying to start again in the world of FOSS, and your seems like a small and nice addition. Can I pick it up?

**Comment by AstroOrbis** [comment]
I don't exactly understand what you mean by "picking it up", sorry;

**Comment by kaustubhmallik** [comment]
Hi, sorry I meant that I would like to work on it. Let me know if it's
possible. 🙂

**Comment by AstroOrbis** [comment]
You can create a fork with your edits, then send a pull request; That would probably the best way for anyone to contribute on this project.

**Comment by AstroOrbis** [comment]
I just updated the project to include a better command switcher, so you should fast-forward your fork BTW :)

**Comment by rishitc** [comment]
Hi @AstroOrbis,
Quick Question: What changes do you have in mind for the _new help menu_? I noticed that you already have the basics set up in the file `main.go`:
```go
	hashTypeFlag := flag.String("hash", "", "Hash flag")
	verboseFlag := flag.Bool("v", false, "Returns verbose output.")
	hashFlag := flag.String("string", "", "Hashes the given string.")

	flag.Parse()
```

Additionally, Go automatically generates the `-h` or `--help` option's output for you [\[1\]](https://gobyexample.com/command-line-flags) (this is a great resource I found mentioned in your source code).

Thanks.

**Comment by AstroOrbis** [comment]
@rishitc,

Thank you! The CLAP library in the new Rust implementation (Dev branch) also takes care of this automatically.

**Comment by rishitc** [comment]
> The CLAP library in the new Rust implementation (Dev branch) also takes care of this automatically.

Thanks for the tip @AstroOrbis;  [CLAP](https://docs.rs/clap/latest/clap/) does look quite interesting.

I'm curious to know if you have any further changes/todos in mind for the `main` branch written in Go. I can help with some unit test cases for the different hash function calls in `main.go`.

**Comment by rishitc** [comment]
Hi @AstroOrbis,
I've created a new PR #8 with unit test cases for the Go implementation of _Hashy_.

Do check out the PR. I would love to hear your feedback!

Thanks

**Comment by DBX12** [comment]
Hi @AstroOrbis,
I'm interested in completing this issue, but I don't want to "steal" the issue from @kaustubhmallik . Could one of you clarify if this issue is worked on or if I could work on it? Thanks :)
I assume by "help menu" you mean a `-help` flag which explains the usage of the application?

**Comment by AstroOrbis** [comment]
@DBX12,
Sorry for the delays, and thank you for your interest on completing the issue.
Yes, this is what I'm looking for. Feel free to work on it!
